### ISSUE TITLE
Update projects to use new GitVersion.yml file

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Home#4]
As suggested by @Jericho

**Comment by gep13** [comment]
This is the suggestion:

```
mode: ContinuousDelivery
branches:
  releases?[/-]:
    mode: ContinuousDeployment
    tag: rc
  dev(elop)?(ment)?$:
    mode: ContinuousDeployment
    tag: alpha
  hotfix(es)?[/-]:
    mode: ContinuousDeployment
    tag: beta
ignore:
  sha: []
```

**Comment by Jericho** [comment]
FYI: when we upgrade to GitVersion 4.0, the content of the yml file would need to be changed to:

```
mode: ContinuousDelivery
branches:
  release:
    regex: releases?[/-]
    mode: ContinuousDeployment
    tag: rc
  develop:
    regex: dev(elop)?(ment)?$
    mode: ContinuousDeployment
    tag: alpha
  hotfix:
    regex: hotfix(es)?[/-]
    mode: ContinuousDeployment
    tag: beta
ignore:
  sha: []
```
